from setuptools import setup, find_packages

setup(
    name="pyfox2x",
    version="0.1.0",
    description="A Python client for SmartFoxServer 2X",
    packages=find_packages(include=["pyfox2x", "pyfox2x.*"]),  # This will find both 'sfs_types' and 'sfs_client'
    install_requires=[
        "requests",  # Add other dependencies here
    ],
)
